name: lambda-calculator
version: '3.0.0.1'
synopsis: A lambda calculus interpreter
description: A simple implementation of the Untyped Lambda Calculus
category: LambdaCalculus,Language,Teaching
author: Sean D Gillespie
maintainer: sean@mistersg.net
copyright: 2016 Sean Gillespie
license: MIT
github: sgillespie/lambda-calculator

dependencies:
  - base >= 4.9 && < 5
  - mtl
  - prettyprinter
  - rio

ghc-options:
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src
  exposed-modules:
    - Language.Lambda.Shared.Errors
    - Language.Lambda.Shared.UniqueSupply
    - Language.Lambda.Untyped
    - Language.Lambda.Untyped.Expression
    - Language.Lambda.Untyped.Eval
    - Language.Lambda.Untyped.Parser
    - Language.Lambda.Untyped.State
    - Language.Lambda.SystemF
    - Language.Lambda.SystemF.Expression
    - Language.Lambda.SystemF.Parser
    - Language.Lambda.SystemF.State
    - Language.Lambda.SystemF.TypeCheck
  dependencies:
    - containers
    - parsec
  
executables:
  lambda-calculator:
    main: Main.hs
    source-dirs: app
    dependencies:
      - bytestring
      - containers
      - lambda-calculator
      - optparse-applicative
      - repline
      - text
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    
tests:
  lambda-calculus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HUnit
      - containers
      - hspec
      - lambda-calculator
      
  lambda-calculus-lint:
    main: HLint.hs
    source-dirs: scripts
    other-modules: []
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hlint
